### ISSUE TITLE
popular EOL taxon page "EOLID:11119143" no longer available.

### ISSUE THREAD

**Issue by jhpoelen** [EOL/tramea#189] opened 2016-03-03 00:07 UTC
As part of an identifier workshop, EOL taxon page/id 11119143, turned up as a highly referenced taxon page id in wiki data (see https://github.com/jhpoelen/id-link-template/blob/master/NOTES.md#small-dataset-phoibos2-manualsemi-auto for more information).

On attempting to figure out whether the EOL taxon page id is, http://eol.org/pages/11119143 was loaded in a browser.

Expected behavior: taxon page with associated information.

Actual result: a login page with the message: "You must be logged in to perform this action. Non-authenticated user does not have access to TaxonConcept with ID=11119143" (see screenshot below).

What can I do to uncover the underlying taxon associated to page id 11119143?

![screen shot 2016-03-02 at 4 05 54 pm](https://cloud.githubusercontent.com/assets/1084872/13480190/faf2c72e-e090-11e5-9f77-6591a919ee1b.png)

**Comment by JRice** [comment] 2016-03-03 02:15
First glance: it was unpublished.

We can learn more about it later, but that much I can confirm.  ;)

**Comment by JRice** [comment] 2016-03-03 15:52
There are NO entries associated with this concept. This leads me to believe it was one of the half-dozen concepts that we "lost" (in actuality, they were merged to unknown other taxon concepts—the merge info was lost) when we encountered a taxon-merging bug a few weeks ago. :(

**Comment by JRice** [comment] 2016-03-03 15:56
Hmmmn... I doubt that, none of those pages look terribly popular. (e.g. http://eol.org/pages/907088/overview ) ...I'd hate to think it was caused by the same bug on an earlier run which was missed!  :S

**Comment by JRice** [comment] 2016-03-03 16:01
LIES! It's published. I'm not sure why the website is reporting it's not.

FTR, this is supposed to be a page for Crinoidea.

Looking into it.

**Comment by JRice** [comment] 2016-03-03 16:05
I see the problem. It's a pretty serious one—we're not following "supercedure" anymore! I see why; fixing.

Thanks for reporting.  ;D

FWIW: this should be redirecting to [page 1960](http://eol.org/pages/1960/overview).

**Comment by JRice** [comment] 2016-03-03 16:12
Fixed.

**Closed as completed by JRice** 2016-03-03 16:12 UTC

**Comment by jhpoelen** [comment] 2016-03-03 16:28
@JRice Thanks acting on this so quickly. I am assuming that the redirect you suggested [eol:1960](http://eol.org/pages/1960) will be put in place at some point in time.

@jhammock @katjaschulz @cmungall @rlwalls2008 @gaurav I think that this issue is a seemingly small, tangible, yet important, outcome of the Phoibos2 workshop in general and identifier linking in specific. . . . and highlights the work ahead of us: id prefix resolving (when wikidata says: eolid:11119143 you can find associated information at http://eol.org/pages/11119143), id usage tracking (where are ids used) etc.
