### ISSUE TITLE
Species being merged to genera, & other substrings, against certain resources

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#220] opened 2016-03-18 21:51 UTC
This has been observed at least twice but is not universal. Several resources have merged cleanly this iteration.

@jrice witnessed [BHL photostream](http://eol.org/content_partners/134/resources/544) merging against the [Clements checklist](http://eol.org/content_partners/570/resources/527) with unexpected substring matches (subspecies merging into species.)

Another pattern was detected last spring, of marine taxa in new resources merging to substrings; I attributed this to WoRMS, mistakenly, I think. In a sample from [Smithsonian Type Data](http://eol.org/content_partners/196/resources/891), of 34 inappropriately merged taxa, [WoRMS](http://eol.org/content_partners/23/resources/26) was present in 13 taxa. OBIS [Depth](http://eol.org/content_partners/257/resources/171) and [Environmental Information](http://eol.org/content_partners/635/resources/692) were present in all and one of them is likely the culprit. (These two resources always appear together. One renders text objects, the other is a TraitBank version of the same content.) 

A sample of appropriately merged taxa from the same resource shows the presence of OBIS does not guarantee an inappropriate merge. The same may be true of Clements. I'll keep digging

**Comment by jhammock** [comment] 2016-03-18 22:20
Ooops, I may have failed to remember a correction. @jrice, did you say "Oh no, wait, that was a self merge" about the [BHL photostream resource](http://eol.org/content_partners/134/resources/544), realizing it was not Clements? The pattern appears to be that all BHL photostream taxa mismapped to substring (genus) names have those names provided in the BHL photostream resource. In [one case](http://eol.org/pages/4389745/names), there are no other hierarchy providers present.

Moving on to how this problem mysteriously does not always happen: a mismapped name has a genus provided in the BHL photostream resource, but a genus provided in the BHL photostream resource does not always result in a mismapped name. Looking only at taxa with the genus provided:

mismapped:
http://eol.org/pages/4389745/names
http://eol.org/pages/18257/names
http://eol.org/pages/45877013/names
http://eol.org/pages/61783/names
http://eol.org/pages/71120/names
http://eol.org/pages/2865674/names
http://eol.org/pages/24149850/names
http://eol.org/pages/20025/names
http://eol.org/pages/24151344/names

not mismapped:
http://eol.org/pages/6540314/names
http://eol.org/pages/18235914/names
http://eol.org/pages/24655130/names

**Comment by jhammock** [comment] 2016-03-19 01:53
If most of the above is correct, I believe the OBIS instance is not a problem, since we should never be merging anything against it ever again. We could test this by harvesting SI Type Data again and leaving OBIS out of the merge. A test would be helpful- much as I find the patterns convincing, I can't find an explanation for _all_ of them, so this is all a theory.

It might still be helpful to know why this happens, to fix BHL photostream if for no other reason. Exploring SI Type Data will probably  turn up more examples not involving the first two culprit resources.

**Comment by JRice** [comment] 2016-03-31 15:23
An example from BHL:

```
** 18-16:56:53.681(6.5) MERGE: concept 44530725 into 18257
** 18-16:56:58.038(4.36) MERGE: concept 44530737 into 18257
** 18-16:57:03.296(5.26) MERGE: concept 44530794 into 18257
** 18-16:57:08.556(5.26) MERGE: concept 44530822 into 18257
** 18-16:57:15.903(7.35) MERGE: concept 44530969 into 18257
** 18-16:57:21.205(5.3) MERGE: concept 45243173 into 18257
** 18-16:57:26.372(5.17) MERGE: concept 45243178 into 18257
** 18-16:57:33.139(6.77) MERGE: concept 45243215 into 18257
** 18-16:57:38.701(5.56) MERGE: concept 45243216 into 18257
** 18-16:57:42.936(4.24) MERGE: concept 45243250 into 18257
** 18-16:57:50.162(7.23) MERGE: concept 45243251 into 18257
** 18-16:57:54.942(4.78) MERGE: concept 45520482 into 18257
** 18-16:57:59.551(4.61) MERGE: concept 45520483 into 18257
** 18-16:58:09.200(9.65) MERGE: concept 45520484 into 18257
** 18-16:58:15.413(6.21) MERGE: concept 45520485 into 18257
** 18-16:58:20.559(5.15) MERGE: concept 45520496 into 18257
** 18-16:58:27.311(6.75) MERGE: concept 45520497 into 18257
** 18-16:58:32.852(5.54) MERGE: concept 45520498 into 18257
** 18-16:58:39.869(7.02) MERGE: concept 45521703 into 18257
```

**Comment by JRice** [comment] 2016-03-31 16:55
Okay, so I found the problem and it's a big one. I've already talked to KS and JH about it, so this is here for posterity:

We're storing entry relationship scores/confidences of 0. This happens when there is a _partial_ match on the canonical form (or scientific name), as in "Loxia" matching against "Loxia ignobilis". This becomes a problem during merging, when we have a clause that says "skip confidences below 0.25, if the match is a synonym match" ... and we have NO such clause for name matches.

There are several ways to solve this:
1. Stop storing scores of 0. This saves Solr some effort, as there's no reason to keep these "non matches".
2. Stop merging if the score is 0.

...I think I'm actually going to do both of those, for completeness (old relationships shouldn't actually be used, but if they were (e.g.: in a manual merge by a developer), having (2) should stop it from being a problem).

...There's also a lingering problem in the database created by this, so we'll need another ticket to investigate that. ...But it should be lower-priority: this problem _should_ be solved with these two small fixes. We'll know as we harvest the next batch of resources.

**Comment by JRice** [comment] 2016-03-31 16:56
I'm hijacking "ready to deploy" as a status for this ticket, since that will keep me from looking at it as something I need to act on, but I don't want to close it until we're confident the problem is resolved (i.e.: after the next batch of harvests). It's really more a status of "done but waiting for confirmation".  :)

**Comment by jhammock** [comment] 2016-05-03 15:38
I feel pretty good about this now. @JRice, ready to close? Or do you want to see a harvest or two first?

**Comment by jhammock** [comment] 2016-05-03 15:47
Oh, I keep forgetting sect. and ser. isn't done; never mind

**Comment by JRice** [comment] 2016-05-03 18:52
I think we can call this ticket done. There's re-merging yet to accomplish, but that's not really causing this issue.

**Closed as completed by JRice** 2016-05-03 18:52 UTC
Labels: bug, priority, V2 wrap up
