### ISSUE TITLE
Image upload in CMS not working

### ISSUE THREAD

**Issue by mariestuder** [EOL/tramea#121] opened 2016-01-28 17:30 UTC
Try to upload an image from a computer in the CMS (for instance, into a Discover article) results in an error.

This is preventing updating of high traffic public facing pages. It is a blocker for work on the Education and Help pages.

**Comment by jhammock** [comment] 2016-01-28 19:05
This has also been noticed by a couple of users, eg: NMNH Nature's Best Photography team, for their collection.

**Comment by mariestuder** [comment] 2016-01-28 19:16
Just to clarify, the original issue is about working in the CMS and not "edit collection details" for Collections. I believe these are two separate issues.  So, perhaps a new ticket is in order?  FWIW, I got Jeremy to fix this problem a couple of weeks ago and it seems to be working for me at the moment.

**Comment by YoustinaAtef** [comment] 2016-01-31 13:15
May you please provide us with the error message and a link to reproduce it if possible?

**Comment by jhammock** [comment] 2016-01-31 16:53
Thanks, @YoustinaAtef ! For instance, at http://eol.org/admin/content_pages/444/translated_content_pages/623/edit, using the Image button in the edit interface. In the Upload tab of the dialog box, after browsing for an image from desktop and selecting "send to server", the error is not fully visible, but inspecting the source shows it to be `http://media.eol.org/content{:response=>"/2016/02/16/16/48458", :error=>nil}_orig.jpg`

@mariestuder , the method available in the Image info tab of that dialog box (sending an image from a url, like a dropbox) seems to be working, see my crustacean larva avatar at the foot of http://eol.org/info/crustaceans (and feel free to remove it)  Is that not working for you, or insufficient to your needs?

**Comment by jhammock** [comment] 2016-02-01 14:29
Oh, @mariestuder is traveling this week. I've marked this one nice-to-have since it may not be blocking L&E's work. @tbarbaroeol, @holmesjtg, let us know if I've missed something above.

**Comment by tbarbaroeol** [comment] 2016-02-02 16:27
This is blocking my work. It would be great if we could fix this.

Tracy Barbaro
Encyclopedia of Life
Harvard University
Museum of Comparative Zoology
26 Oxford Street
Cambridge, MA 02138 USA
Phone: 617.496.6764
Fax:  (617)  495-5667

**Comment by jhammock** [comment] 2016-02-02 17:02
Manual server storage of these files is a plausible workaround for now. Would be nice if that didn't have to continue until Tramea.

**Comment by JRice** [comment] 2016-02-16 21:42
Looking at the error, I can see this is actually a pretty quick fix: we just need to alter how we handle the response (which seems to have added an "error" node to its response hash since this code was written). Lemme see if I can find that...

**Comment by JRice** [comment] 2016-02-16 21:43
(I will also take the opportunity to carp—again—that this is a stupid problem to have and the only reason we have it is because of the (stupid) lack of a shared filesystem across servers.)

**Comment by JRice** [comment] 2016-02-16 21:53
Totally archaic part of the code, this will not be simple.

**Comment by jhammock** [comment] 2016-02-16 22:15
If it's not easy, we can wait for Tramea. The workaround is easy.

**Comment by JRice** [comment] 2016-02-16 22:20
Too late; I found it. Wasn't easy, I'll say... it was really, really, _really_ buried. Completely non-obvious. Honestly, I'm not even sure what it's doing to get where it's getting. This is truly ridiculous code (again: to circumvent the lack of shared content).

That said, this _should_ be fixed on beta.eol.org (e.g. the [page mentioned earlier](http://beta.eol.org/admin/content_pages/444/translated_content_pages/623/edit))...Which, BTW, is _live data_, so if you add content there, it will be on the live site.

Could someone confirm it's working?

It'll be fixed on "normal" EOL once we do our next deploy.

**Comment by jhammock** [comment] 2016-02-16 22:34
Sorry, just tried an upload from desktop to http://beta.eol.org/admin/content_pages/445/translated_content_pages/624/edit and I'm not seeing it. (there should be an image filename="12 elephant snail.jpg" sitting near the bottom, beside the header for References)

It did seem to be working while I was in the edit interface, but there's no trace of it now in edit or view.

**Comment by JRice** [comment] 2016-02-16 23:11
[sigh]

Separate problem. It looks like nothing is being saved to that particular page (at least that page). Even plain-text edits aren't saved.

Sorry, I don't understand this system, so I cannot be sure this is how it works; do you need to "unpublish" it first, or create a new version or something? 

Nope, it's not saving, even from the command-line. I'm really not sure what's going on, here. Frustrating.

[raises hands] not going to fix this (second problem) tonight. I'm pretty sure the reason for this ticket is fixed, though. :(

**Comment by JRice** [comment] 2016-02-16 23:17
```
ActionView::Template::Error (undefined method `id' for nil:NilClass):
    2: %ul#collection_items.object_list
    3:   - @collection_items.each do |item|
    4:     - item_type = en_type(item)
    5:     %li{class: item_type, id: "collection_item_#{item.id}"}
    6:       = render 'collection_items/show', { :collection_item => item, :item_type => item_type,
    7:         :view_style => 'annotated', :item_editable => editable,
    8:         is_hidden: ['image_map', 'map', 'image', 'video', 'sound', 'link', 'article'].include?(item_type) && item.is_hidden?  }
  app/views/collections/_show_annotated_style.html.haml:5:in `block in _app_views_collections__show_annotated_style_html_haml__2001904726292938680_44313980'
  app/views/collections/_show_annotated_style.html.haml:3:in `each'
  app/views/collections/_show_annotated_style.html.haml:3:in `_app_views_collections__show_annotated_style_html_haml__2001904726292938680_44313980'
  app/views/collections/show.html.haml:67:in `block in _app_views_collections_show_html_haml__34024609985757996_94564440'
  app/views/collections/show.html.haml:42:in `_app_views_collections_show_html_haml__34024609985757996_94564440'
```

**Comment by jhammock** [comment] 2016-02-17 16:43
Attempting this kind of edit in a different CMS article threw an error message beginning "24025, :error=>nil} orig"

We can live without this fix until Tramea. Text edits to other CMS articles are still working.

**Comment by tbarbaroeol** [comment] 2016-02-17 17:02
Hi All
I just uploaded an image to beta.eol.org and it is visible on the same page
in eol.org
This fix should work for my purposes until Tramea...
Thanks!
TB

Tracy Barbaro
Encyclopedia of Life
Harvard University
Museum of Comparative Zoology
26 Oxford Street
Cambridge, MA 02138 USA
Phone: 617.496.6764
Fax:  (617)  495-5667

**Comment by jhammock** [comment] 2016-02-17 17:06
Silly me, I was on the non beta. Good! If the mollusks page is uniquely frozen, I think we can live with that.

**Closed as completed by jhammock** 2016-02-17 17:06 UTC
Labels: bug, nice-to-have
